#!/usr/bin/env python3

if __name__ == '__main__':
    # This conditional checks if the script is being run as the main program.
    # It ensures that the following code block is only executed when the script
    # is run directly and not when it is imported as a module in another script.

    import numpy as np
    # Import the NumPy library and alias it as 'np'. NumPy is a popular library
    # for numerical operations on arrays and matrices.

    from multinormal import MultiNormal
    # Import the 'MultiNormal' class from the 'multinormal' module.

    np.random.seed(0)
    # Set the random seed for reproducibility. This ensures that random numbers
    # generated by NumPy will be the same every time the script is run.

    data = np.random.multivariate_normal([12, 30, 10], [[36, -30, 15], [-30, 100, -20], [15, -20, 25]], 10000).T
    # Generate a random dataset 'data' using NumPy's 'multivariate_normal' function.
    # This data is drawn from a multivariate normal distribution with specified mean
    # and covariance matrix. The result is transposed for further processing.

    mn = MultiNormal(data)
    # Create an instance of the 'MultiNormal' class, passing the 'data' as input.

    print(mn.mean)
    # Print the mean vector of the dataset.

    print(mn.cov)
    # Print the covariance matrix of the dataset.

